language: minimal

addons:
  apt:
    packages:
    - libdevel-cover-perl

before_script: cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov

script: make test

after_success: cover -test -report codecov
