#!/usr/bin/env perl

use strict;
use warnings;
use feature qw(say);
use Getopt::Long qw(GetOptionsFromArray);
use Semver;

sub usage() {
    my $program = "semver-compare";

    say STDERR "Semantic Versioning utility.";
    say STDERR "";
    say STDERR "Usage:";
    say STDERR "  $program [options] <version> <version>";
    say STDERR "";
    say STDERR "Options:";
    say STDERR "  -h --help  Show this help screen.";

    exit 1;
}

sub main {
    my @args = @_;

    my $help;
    GetOptionsFromArray(\@args, "help|h" => \$help) or exit 1;

    if ($help) {
        usage();
    } else {
        say Semver::compare($args[0], $args[1]);
    }
}

main(@ARGV);
