#!/usr/bin/env perl

use strict;
use warnings;
use feature qw(say);
use Scalar::Util qw(looks_like_number);
use List::Util qw(max);

# Regex from semver.org: https://github.com/semver/semver/pull/460
my $semver_regex = '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$';
my $semver_precedence_regex_head = '^([0-9a-zA-Z-]*)';
my $semver_precedence_regex_tail = '\.(0|[1-9a-zA-Z-][0-9a-zA-Z-]*)';

my $gt = 1;
my $eq = 0;
my $lt = -1;

sub usage() {
    my $program = "semver";

    say STDERR "Semantic Versioning utility.";
    say STDERR "";
    say STDERR "Usage:";
    say STDERR "  $program compare <version> <version>";
    say STDERR "  $program decrement-major <version>";
    say STDERR "  $program decrement-minor <version>";
    say STDERR "  $program decrement-patch <version>";
    say STDERR "  $program get-major <version>";
    say STDERR "  $program get-minor <version>";
    say STDERR "  $program get-patch <version>";
    say STDERR "  $program get-prerelease <version>";
    say STDERR "  $program get-build <version>";
    say STDERR "  $program grep -";
    say STDERR "  $program increment-major <version>";
    say STDERR "  $program increment-minor <version>";
    say STDERR "  $program increment-patch <version>";
    say STDERR "  $program init";
    say STDERR "  $program sort -";
    say STDERR "  $program validate <string>";
    say STDERR "  $program (-h | --help)";
    say STDERR "";
    say STDERR "Options:";
    say STDERR "  -h --help  Show this help screen.";

    exit 1;
}

sub semver_get {
    my ($str) = @_;

    my @matches = $str =~ $semver_regex;

    if ((defined $matches[0]) && (defined $matches[1]) && (defined $matches[2])) {
        return @matches;
    } else {
        exit 1
    }
}

sub semver_get_prerelease_identifiers {
    my ($prerelease) = @_;

    my @prerelease_identifiers_first = $prerelease =~ /$semver_precedence_regex_head/;
    my @prerelease_identifiers_rest = $prerelease =~ /$semver_precedence_regex_tail/g;

    push(@prerelease_identifiers_first, @prerelease_identifiers_rest);

    return @prerelease_identifiers_first;
}

sub semver_compare_prerelease_identifier {
    my ($a, $b) = @_;

    if ((defined $a) && (defined $b)) {
        if (looks_like_number($a) && looks_like_number($b)) {
            if ($a > $b) {
                return $gt;
            } elsif ($a < $b) {
                return $lt;
            }
        } elsif (!looks_like_number($a) && looks_like_number($b)) {
            return $gt;
        } else {
            my $a_cmp_b = $a cmp $b;

            if ($a_cmp_b eq 1) {
                return $gt;
            } elsif ($a_cmp_b eq -1) {
                return $lt;
            }
        }
        return $eq;
    } elsif ((defined $a) && (!defined $b)) {
        return $gt;
    } elsif ((!defined $a) && (defined $b)) {
        return $lt;
    }
}

sub semver_compare_prerelease {
    my ($a, $b) = @_;

    if ((!defined $a) && (defined $b)) {
        return $gt;
    } elsif ((defined $a) && (!defined $b)) {
        return $lt;
    } elsif ((defined $a) && (defined $b)) {
        my @a_identifiers = semver_get_prerelease_identifiers($a);
        my @b_identifiers = semver_get_prerelease_identifiers($b);

        for (my $i = 0; $i < max(scalar(@a_identifiers), scalar(@b_identifiers)); $i++) {
            my $a_identifier = $a_identifiers[$i];
            my $b_identifier = $b_identifiers[$i];

            my $a_cmp_b = semver_compare_prerelease_identifier($a_identifier, $b_identifier);

            if ($a_cmp_b eq 1) {
                return $gt;
            } elsif ($a_cmp_b eq -1) {
                return $lt;
            }
        }

        return $eq;
    } else {
        return $eq;
    }
}

sub semver::compare {
    my ($a, $b) = @_;

    my @a_matches = semver_get($a);

    my $a_major = $a_matches[0];
    my $a_minor = $a_matches[1];
    my $a_patch = $a_matches[2];
    my $a_prerelease = $a_matches[3];

    my @b_matches = semver_get($b);

    my $b_major = $b_matches[0];
    my $b_minor = $b_matches[1];
    my $b_patch = $b_matches[2];
    my $b_prerelease = $b_matches[3];

    if ($a_major > $b_major) {
        return $gt;
    } elsif (($a_major eq $b_major) && ($a_minor > $b_minor)) {
        return $gt;
    } elsif (($a_major eq $b_major) && ($a_minor eq $b_minor) && ($a_patch > $b_patch)) {
        return $gt;
    } elsif (($a_major eq $b_major) && ($a_minor eq $b_minor) && ($a_patch eq $b_patch)) {
        return semver_compare_prerelease($a_prerelease, $b_prerelease);
    } else {
        return $lt;
    }
}

sub semver::decrement_major {
    my ($version) = @_;

    my @matches = semver_get($version);

    my $major = $matches[0];

    if ($major > 0) {
        my $new_major = $major - 1;
        say "$new_major.0.0";
    } else {
        exit 1;
    }
}

sub semver::decrement_minor {
    my ($version) = @_;

    my @matches = semver_get($version);

    my $major = $matches[0];
    my $minor = $matches[1];

    if ($minor > 0) {
        my $new_minor = $minor - 1;
        say "$major.$new_minor.0";
    } else {
        exit 1;
    }
}

sub semver::decrement_patch {
    my ($version) = @_;

    my @matches = semver_get($version);

    my $major = $matches[0];
    my $minor = $matches[1];
    my $patch = $matches[2];

    if ($patch > 0) {
        my $new_patch = $patch - 1;
        say "$major.$minor.$new_patch";
    } else {
        exit 1;
    }
}

sub semver::get_major {
    my ($version) = @_;

    my @matches = semver_get($version);

    say $matches[0];
}

sub semver::get_minor {
    my ($version) = @_;

    my @matches = semver_get($version);

    say $matches[1];
}

sub semver::get_patch {
    my ($version) = @_;

    my @matches = semver_get($version);

    say $matches[2];
}

sub semver::get_prerelease {
    my ($version) = @_;

    my @matches = semver_get($version);

    say $matches[3];
}

sub semver::get_build {
    my ($version) = @_;

    my @matches = semver_get($version);

    say $matches[4];
}

sub semver::grep {
    while (my $line = <STDIN>) {
        my @words = split(/\s+/, $line);
        foreach (@words) {
            if (/$semver_regex/) {
                print "$1.$2.$3";
                print "-$4" if (length $4 // '');
                print "+$5" if (length $5 // '');
                print "\n";
            }
        }
    }
}

sub semver::increment_major {
    my ($version) = @_;

    my @matches = semver_get($version);

    my $major = $matches[0];
    my $new_major = $major + 1;

    say "$new_major.0.0";
}

sub semver::increment_minor {
    my ($version) = @_;

    my @matches = semver_get($version);

    my $major = $matches[0];
    my $minor = $matches[1];
    my $new_minor = $minor + 1;

    say "$major.$new_minor.0";
}

sub semver::increment_patch {
    my ($version) = @_;

    my @matches = semver_get($version);

    my $major = $matches[0];
    my $minor = $matches[1];
    my $patch = $matches[2];
    my $new_patch = $patch + 1;

    say "$major.$minor.$new_patch";
}

sub semver::init {
    say "0.0.0";
}

sub semver::sort {
    my @lines = <STDIN>;
    chomp(@lines);

    if (scalar(@lines) eq 1) {
        # Validate manually if just 1 line, because Perl sort does not kick in until it has at least 2 elements.
        my $line = $lines[0];
        if ($line =~ /$semver_regex/) {
            say $line;
        } else {
            exit 1;
        }
    } elsif (scalar(@lines) > 1) {
        my @sorted_lines = sort {
            my $res = semver::compare($a, $b);

            if ($res eq $gt) {
                return $gt;
            } elsif ($res eq $lt) {
                return $lt;
            } else {
                # Extra sorting for precedence-equal but stringwise-unequal version strings.
                return $a cmp $b;
            }
        } @lines;

        say join "\n", @sorted_lines;
    }
}

sub semver::validate {
    my ($str) = @_;

    ($str =~ /$semver_regex/) ? exit 0 : exit 1;
}

sub main {
    my @args = @_;

    if (scalar(@args) < 1) {
        usage();
    }

    my $subcommand = $args[0];

    if ($subcommand eq "grep") {
        semver::grep();
    } elsif ($subcommand eq "init") {
        semver::init();
    } elsif ($subcommand eq "decrement-major") {
        semver::decrement_major($args[1]);
    } elsif ($subcommand eq "decrement-minor") {
        semver::decrement_minor($args[1]);
    } elsif ($subcommand eq "decrement-patch") {
        semver::decrement_patch($args[1]);
    } elsif ($subcommand eq "get-major") {
        semver::get_major($args[1]);
    } elsif ($subcommand eq "get-minor") {
        semver::get_minor($args[1]);
    } elsif ($subcommand eq "get-patch") {
        semver::get_patch($args[1]);
    } elsif ($subcommand eq "get-prerelease") {
        semver::get_prerelease($args[1]);
    } elsif ($subcommand eq "get-build") {
        semver::get_build($args[1]);
    } elsif (($subcommand eq "-h") || ($subcommand eq "--help")) {
        usage();
    } elsif ($subcommand eq "increment-major") {
        semver::increment_major($args[1]);
    } elsif ($subcommand eq "increment-minor") {
        semver::increment_minor($args[1]);
    } elsif ($subcommand eq "increment-patch") {
        semver::increment_patch($args[1]);
    } elsif ($subcommand eq "sort") {
        semver::sort();
    } elsif ($subcommand eq "validate") {
        semver::validate($args[1]);
    } elsif ($subcommand eq "compare") {
        say semver::compare($args[1], $args[2]);
    } else {
        usage();
    }
}

main(@ARGV);
