name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install APT dependencies
        run: sudo apt-get install bats libdevel-cover-perl
      - name: Install CPAN dependencies
        run: cpanm --sudo --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov
      - name: Test
        run: PERL5OPT=-MDevel::Cover make test
      - uses: codecov/codecov-action@v1
