name: Build Debian package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jiro4989/build-deb-action@v2
        with:
          package: semver
          package_root: .debpkg
          maintainer: Chris Kilding
          version: '0.0.0'
          arch: 'amd64'
          desc: 'Semantic Versioning utility'
